import Head from "next/head";

export const metadata = {
  title: "Coffee Shop ",
  description: "Generated by Next.js",
  icons: {},
};

export default function RootLayout({
  children,
}: {
  children: React.ReactElement;
}) {
  return (
    <html lang="en">
      <body>
        <main>{children}</main>
      </body>
    </html>
  );
}
